### ISSUE TITLE
socket.io 1.0 support?

### ISSUE THREAD

**Issue by adrai** [jstott/socketio4net#2]
Do you plan to support socket.io 1.0 ?

**Comment by jstott** [comment]
Yes, whenever that may be.  Last [thread](https://groups.google.com/forum/#!topic/socket_io/vwZDG-AmGhk) I saw by Guillermo was on Dec 10th - will just have to wait and see.

**Comment by adrai** [comment]
ok, thanks for feedback...

**Comment by adrai** [comment]
@jstott https://github.com/LearnBoost/socket.io/issues/1470#issuecomment-42247496

**Comment by alvinteh** [comment]
Socket.IO 1.0 was released a few days ago - now that it is official, are there any plans to update this library to support that?
