### ISSUE TITLE
Client Connect seems to hang if server is unavailable

### ISSUE THREAD

**Issue by Kronos87** [jstott/socketio4net#6]
Hello, first of all thanks for the great implementation.
I got a problem with the client.Connect() method. If the server is offline/unavailable, the Connect() method seems to hang, the program does not go further anymore. I tried to set the number of reconnects to certain values (0, 1) but it did not help. There is even no exception thrown. What can I do?

**Comment by jstott** [comment]
Project will no longer be maintained.
