### ISSUE TITLE
Handshake error when connecting to a socket.io 1.0 server

### ISSUE THREAD

**Issue by sunsided** [jstott/socketio4net#7]
When connecting to a socket.io 1.0 server (Express 3, node.js 0.10), the connection attempt fails with a "Error initializing handshake" message.

The socket.io documentation says in [http://socket.io/docs/migrating-from-0-9/](http://socket.io/docs/migrating-from-0-9/#parser-/-protocol-differences) that some protocol changes happened.

**Comment by cschloesser** [comment]
That is known and there are 2 closed issues for that. Unfortunately no updates on that topic! jstott said that he has plans to do it, but is really buys.

We switched to 0.9.16 because we need it, but of course we would prefer 1.0

**Comment by jstott** [comment]
FYI - I've decided to stop maintaining this project...If anyone wants to pickup where I left off, PM me.  [Short discussion on codeplex ](http://socketio4net.codeplex.com/discussions/554789)
